### ISSUE TITLE
Back and Next change month links not working anymore on page embedded calendars

### ISSUE THREAD

**Issue by aspeer06** [pderksen/WP-Google-Calendar-Events#26]
WP: Version 4.1
Google Calendar Events: Version 2.1.7
SITE_URL:                 http://www.maryville.lib.il.us
HOME_URL:                 http://www.maryville.lib.il.us
THEME | VERSION :         Customizr | v3.2.15
WP VERSION :              4.1
PERMALINK STRUCTURE :     /%year%/%monthnum%/%postname%/
ACTIVE PLUGINS :
Better WordPress Google XML Sitemaps: 1.3.1
Childify Me: 1.0.2
Easy Pie Maintenance Mode: 0.6.4
Easy Responsive Shortcodes: 1.0.1
Enhanced Media Library: 2.0.3
Google Calendar Events: 2.1.7
Google Calendar Widget: 1.4.6
Regenerate Thumbnails: 2.2.4
RSS Includes Pages: 1.4.3
TablePress: 1.5.1
UpdraftPlus - Backup/Restore: 1.9.46
WP Super Cache: 1.4.2
PHP Version:              5.4.36

Non working items: http://www.maryville.lib.il.us/eventscalendar/
Working in widget still: http://www.maryville.lib.il.us/ (lower left of page)

**Comment by nickyoung87** [comment]
Does it work if you disable your other plugins and use a default theme? It is possible there is a conflict with another plugin that we need to narrow down.

**Comment by aspeer06** [comment]
I deactivated all the plugins and changed themes with now luck, any other ideas? I was working up until sometime after Jan 8th.

**Comment by nickyoung87** [comment]
@aspeer06 Sorry for the delay here. It looks like you have some sort of caching going on is that correct? Does it make any difference if you change some of your caching settings to not cache the javascript?

**Comment by aspeer06** [comment]
Removed the caching completely and still having issues :/

**Comment by nickyoung87** [comment]
We did some work with the JS for an upcoming release. I will check back after the release to see if the update helps with the issue you are having.

Thanks for your patience!

**Comment by aspeer06** [comment]
No problem at all, I test it on a second scratch site without anything else enabled and it did work there either for what it's work. Could be an issue with Dreamhost as it works on a locally hosted instance.

**Comment by nickyoung87** [comment]
@aspeer06 Hmm that is interesting. It must be something interfering if it works on a fresh install. If you narrow it down please do let us know so we can look into it.

We also just pushed a new stable release if you want to give that a shot.

Thanks!
