### ISSUE TITLE
Minor logic flaw for limiting the number of days displayed in lists

### ISSUE THREAD

**Issue by coldhawaiian** [pderksen/WP-Google-Calendar-Events#27]
I've been debugging the code used to determine how many days worth of events to display in the list views, and I think I may have discovered a minor flaw in the logic. I'm referring specifically to [line 329 in the `GCE_Display` class][bug]:

```php
$event->end_time   <= $end_time ) ||
```

The logic for displaying a day in that conditional should basically be like this (in pseudo-code):

> IF the event starts between the beginning of the date range (inclusive) AND the end of the date range (exclusive)

The problem with the conditional as it is now is that it compares the event start with the end date ***inclusively***, with `<=`, not exclusively, which would be `<`.

If the exclusive end-date of my calendar is "Sunday, February 1st, 2014 00:00:00", for example, then an event occurring at midnight on February 1st should not appear in a list of events for 7 days that begins with the previous Sunday, January 25th. Saturday, Jan 31st should be the last day displayed (until paged to the next week), but the inclusive end-date logic above would end up including the event occurring at midnight on Feb 1st.

Am I right, or am I misunderstanding the code?

[bug]: https://github.com/pderksen/WP-Google-Calendar-Events/blob/v2.1.7/google-calendar-events/includes/class-gce-display.php#L329

**Comment by coldhawaiian** [comment]
I discussed the issue with the dev over on [WordPress.org][wordpress] as well.

[wordpress]: https://wordpress.org/support/topic/number-of-events-per-page-logic-error-with-end-dates

**Comment by nickyoung87** [comment]
@coldhawaiian Is it possible you can send me an example of this happening for you? Also, include a direct link to the calendar if you can so I can compare the dates.

I just setup a test for this but I am not getting the extra day at the end like you mention. Another thing to double check is your timezone settings are correct.

Let me know so I can investigate further.

**Comment by coldhawaiian** [comment]
Hi @nickyoung87. I can't send you a live example from my site, because I patched the line in question to be

```php
$event->start_time <= $end_time ) ||
```

I can, however, send you a link to the Google Calendar that I'm using, along with my plugin settings. [Here's the calendar link][calendar]. And these are my plugin settings:

**Markup**
```html
<div class="gce-list-event gce-tooltip-event">[event-title]</div>
<div>Starts: [start-time]</div>
<div>Ends: [end-date] [end-time]</div>
[if-location]
<div>Location: [location]</div>
[/if-location]
[if-description]
<div>[description]</div>
[/if-description]
```

**Settings**
![image](https://cloud.githubusercontent.com/assets/463580/5970981/fed1e0ea-a7df-11e4-91b5-e63824076b76.png)

![image](https://cloud.githubusercontent.com/assets/463580/5970987/0fcc20a4-a7e0-11e4-8fcd-3d6e2e61dc88.png)

![image](https://cloud.githubusercontent.com/assets/463580/5970990/1f9abc52-a7e0-11e4-8eca-0352eb396887.png)

I tried out using different timezones with my WordPress installation to see if that might be the cause of the issue, but I couldn't seem to fix it by just adjusting that setting in WordPress:

![image](https://cloud.githubusercontent.com/assets/463580/5971002/667948f0-a7e0-11e4-943f-9445ac29d147.png)

I can try playing around with the timezone again over the weekend though to see if I missed something. Let me know if there's anything else you need that can help.

[calendar]: https://www.google.com/calendar/embed?src=boston.salsa.scene%40gmail.com&ctz=America/New_York

**Comment by nickyoung87** [comment]
@coldhawaiian Thanks for the reply and all the extra info. Did the patch you added in actually fix the problem for you?

**Comment by coldhawaiian** [comment]
@nickyoung87 as far as I can tell, yes, it fixed the issue, the calendar [displays 7 days worth of events][link], even on Sundays. But that's just with my particular settings, I haven't tested it using different values for the settings and seeing if things still work properly.

I haven't tested it out with different days of the week yet either, just Sunday...I guess I'll have to mess around with my local system clock in my dev environment just to double check that things are working the way that they're supposed to.

Oh, and I forgot to mention, the target timezone for the calendar in East Coast time in the United States, UTC-5.

[link]: http://bostonsalsa.info/calendar/

**Comment by nickyoung87** [comment]
@coldhawaiian Thanks for the additional information. I was just curious if maybe this is something I should add in to the code officially if it is fixing the issue. I will do some testing on it as well. Thanks!

**Comment by nickyoung87** [comment]
@coldhawaiian Is the change I made recently what you had done?

https://github.com/pderksen/WP-Google-Calendar-Events/commit/3a540c7630aaa787dc2b16b87697e0e027ace60b

**Comment by nickyoung87** [comment]
@coldhawaiian We just pushed a new stable release with the fix above in this area. Let us know if you have any more issues.

Thanks!
