### ISSUE TITLE
Gray box surrounding list view entries after update

### ISSUE THREAD

**Issue by ToddAu** [pderksen/WP-Google-Calendar-Events#28]
I am running v2.1.1 and following the update to 2.1.7, all of the entries in the list view now have a gray background where previously no background existed.  I have tried to sort through the CSS, but cannot find the issue.  Also, I also had trouble adjusting the font for the list view text in 2.1.7, but was able to easily change it 2.1.1.  I have reverted back to 2.1.1, but would love to take advantage of some of the features in the newer version.  Any insight on how to easily remove the gray background and adjust the font of the list view entries would be great.

**Comment by nickyoung87** [comment]
@ToddAu 

For the gray box you should be able to use:

.gce-list-event { background: none; } 

You will need to add that in your theme stylesheet. You should be able to modify the font with the CSS too but I don't think we set it except for the tooltip hovers so it might be coming from your theme. If you post a link to it here I can take a look for you.
