### ISSUE TITLE
Problem with version 2.2.0 

### ISSUE THREAD

**Issue by PeterHarvey** [pderksen/WP-Google-Calendar-Events#29]
I am using version 2.1.6 to display calendar details on my website http://hemblingtonchurch.org.uk

When I upgraded to version 2.2.0 the calender data was still displayed but it lost all the formatting. There was just a list of dates and events all in the same text colour and with the same background. I reverted the plugin by copying the plugin folder from a backup and everything was working correctly again.

Please let me know what information you require to investigate this further.

**Comment by PeterHarvey** [comment]
Apologies website address should be http://hemblingtonchurch.org.uk

**Comment by pderksen** [comment]
We just pushed an update to the plugin (2.2.1) that may fix the issue.

**Comment by PeterHarvey** [comment]
Thanks that seems to have addressed the problem

**Comment by pderksen** [comment]
Glad it worked.
