### ISSUE TITLE
Can no longer dequeue stylesheet with wp_print_styles action

### ISSUE THREAD

**Issue by martinburchell** [pderksen/WP-Google-Calendar-Events#31]
In my theme I dequeue the default google calendar events style sheet with a 'wp_print_styles' action.

Since 2.2.1 the style sheet is enqueued again in the 'the_posts' filter. As a workaround I can also dequeue the style sheet with a 'the_posts' filter but this doesn't seem optimal to me.

**Comment by pderksen** [comment]
How about we add an option to disable all plugin CSS (independent of the JS)? We've done this for other plugins.

**Comment by martinburchell** [comment]
That would be fine. In fact I think there used to be an option to do this.
