### ISSUE TITLE
css position after update to 2.2.2

### ISSUE THREAD

**Issue by jaylinski** [pderksen/WP-Google-Calendar-Events#32]
hi there!

after the update to v2.2.2, the plugin-css is getting loaded *after* my child-theme css.
therefore the css overrides in my child-theme did not work anymore. i had a hard time figuring out how to fix this, this is my solution:
```
add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );
function theme_enqueue_styles() {
	$deps = array();
	if(wp_style_is('google-calendar-events-public', 'registered')) {
		$deps[] = 'google-calendar-events-public';
	}
	wp_enqueue_style( 'parent-style', get_template_directory_uri() . '/style.css', $deps );
}
```
i thought you maybe wanted to share this in your docs (http://wpdocs.philderksen.com/google-calendar-events/misc/theme-and-plugin-conflicts/)

p.s.: thx for the awesome plugin!

**Comment by pderksen** [comment]
@jaylinski I just tested this out and my test site's plugin CSS is always getting loaded after parent theme, child theme and custom css injected from Jetpack's css editor.

I wonder if you have some other priority setting in your theme or config somewhere.

In any case glad you found a fix and glad you like the plugin. :)

**Comment by jaylinski** [comment]
thx for the feedback! it's probably caused by my parent theme (Hueman).
