### ISSUE TITLE
Compound view to see Grid and Grouped list at the same time

### ISSUE THREAD

**Issue by motiteux** [pderksen/WP-Google-Calendar-Events#33]
This is a suggestion for an enhancement.

It would be nice to have a view where you could see both the Grid view and the Grouped list in the same page. Thus, when the user click on next, it would synchronize the month from the calendar view to the list of displayed events. 

The real problem here is that the calendar view does not show the name of the events unless you mouseover the cells. And from the list view, it is usual to get a spatial representation of the events in a calendar. 

Thanks a lot for the plugin though, it is really nice.

**Comment by pderksen** [comment]
That's definitely the top feature request on our roadmap, so we're definitely planning on it.

https://trello.com/b/ZQSzsarY

Feel free to vote and contribute and thanks for the compliment!
