### ISSUE TITLE
Events in the Grid View Widget Displaying Wrong Time

### ISSUE THREAD

**Issue by STCAAdmin** [pderksen/WP-Google-Calendar-Events#34]
Yesterday, I noticed that the times on all of the items in the grid view calendar beyond the current month are displaying as 7 hours later than they are on the source Google Calendar. Underneath the grid view widget, I have a list view widget pulling the same items from the same calendar, but all of the times are displaying correctly in the list view even after getting rid of cache. They are different feeds, but the same source calendar. I have tried creating a new feed with identical settings to the one having issues, but when I display that feed, ALL the events displayed show the times as 7 hours later. I have tried deleting the cache, creating new feeds, and making sure any timezone settings are correct without any luck. If you would like to see what is going on, the school's website is http://stcatherinemh.org.

**Comment by nickyoung87** [comment]
Does it work properly if you disable your other plugins and use a default theme?

**Comment by STCAAdmin** [comment]
I located the issue. The date/time settings in Wordpress general settings was showing but not using the correct timezone. I saved the timezone as something else, then changed it back. This seems to have fixed the issue. Sorry for wasting your time.

**Comment by nickyoung87** [comment]
@STCAAdmin Awesome, glad to hear you found the fix. Thanks for letting us know!
