### ISSUE TITLE
Time not displayed correctly

### ISSUE THREAD

**Issue by PeterHarvey** [pderksen/WP-Google-Calendar-Events#35]
I am displaying my events as a grouped list. Today there are events over the next few days some of which take place after the clocks change on Sunday to implement day light saving hours. The events that take place after the clocks have changed are being displayed with the time one hour out. Is it possible that there is one check for daylight saving at the start rather than checking before displaying each entry.Or is there some setting in Wordpress or Google that I have not set correctly. You can see the problem at:

http://www.blofieldchurch.org.uk

**Comment by PeterHarvey** [comment]
Problem has disappeared. No idea why as clocks have not moved forward yet. I had upgraded the plugin to latest version and checked the problem was still there before reporting it. I haven't changed anything since.

**Comment by pderksen** [comment]
Strange. Thanks for letting us know and please speak up if it happens again.
