### ISSUE TITLE
Recurring event not being displayed

### ISSUE THREAD

**Issue by Sukasa** [pderksen/WP-Google-Calendar-Events#36]
I use this plugin on a wordpress installation for Makerspace Nanaimo.  Overall the plugin works great and has been smooth, however we just found out that a single recurring event tonight is not being listed in the calendar.  Other events in that series are showing up, however this is the only one to land on the last day of the month in the time that we have been using the plugin.

You can see the feed in action at https://makerspacenanaimo.org/gce_feed/220/.

The feed is set up to properly expand recurring events, and is doing so fine for other such events.

**Comment by nickyoung87** [comment]
@Sukasa 
That is weird. I assume you are talking about the list in the main content here. What do you have your "Events per Page" settings set to? I noticed on some pages it is showing 8 days and then the week in question shows 6 days instead of 6. Is this a correct assessment?

**Comment by nickyoung87** [comment]
@Sukasa 
Actually I also want to double check that you have the WordPress timezone settings set to the correct setting as well.

**Comment by Sukasa** [comment]
Hi, Nick.

I have to apologize as this appears to be a problem on our end - one member did something that changed the calendar - when we checked the calendar, some members were seeing specific events and other members (and the plugin) were not seeing them.  We've fixed it on our end and the events are now showing up.

In short, a couple PEBKACs.

**Comment by nickyoung87** [comment]
@Sukasa Ah ok, glad it got worked out. Thanks for updating us.
