### ISSUE TITLE
Time display out by one hour

### ISSUE THREAD

**Issue by PeterHarvey** [pderksen/WP-Google-Calendar-Events#37]
The problem I reported before has returned. All events are being displayed with the time out by one hour. In Google calendar the events are entered using the London time zone and are displayed correctly i.e. 6 am, 9.30am, 11am, Currently in the plugin all the events are being displayed 1 hour early i.e. 5am, 8.30am, 10am. I have tried setting the cache to 1 second and I have tried on different browsers across a windows PC and iPad but the problem is still there. I have tried adding an event but this is just displayed again with the wrong time.
![image](https://cloud.githubusercontent.com/assets/11245610/6992058/f0bb146a-daaf-11e4-9bca-02ee01a8555a.png)
Web site is http://www.hemblingtonchurch.org.uk

Peter

**Comment by PeterHarvey** [comment]
Interestingly I have another website with the same setup running on the same server and using the same Google calendar and this is displaying the times correctly.

http://www.blofieldchurch.org.uk

I am using version 2.2.3 of the plugin
Peter

**Comment by nickyoung87** [comment]
Sorry for the delay here.

What do you have your timezone settings in WordPress set to? The plugin also uses that option for displaying the times.

**Comment by PeterHarvey** [comment]
I have found the problem. The site that works has the timezone set to London but the site that doesn't was set to UTC+0. Set the problem site to London and all is now working. I was looking just at the plugin settings.

Thanks

**Comment by nickyoung87** [comment]
Awesome, glad to hear that solved it! Thanks for letting us know.
