### ISSUE TITLE
No dates displayed in widget - list view

### ISSUE THREAD

**Issue by Natalieponting** [pderksen/WP-Google-Calendar-Events#39]
I have a widget showing events in my homepage sidebar. It's in list view and shows all relevant information except the event date. How can I add this?

**Comment by nickyoung87** [comment]
What do you have set for the event builder codes. It should have a [start-time], [start-date] or something similar in there. Does yours have that?

Here is some more info on the event builder codes: http://wpdocs.philderksen.com/google-calendar-events/event-builder/

**Comment by nickyoung87** [comment]
@Natalieponting I am going to assume that this got resolved since there hasn't been a reply from you here lately. Please let us know if you continue to have issues or run into anything else.

Thanks!

**Comment by Natalieponting** [comment]
Hi Nick
Sorry - I have indeed resolved the issue. Many thanks for your help.
Natalie
