### ISSUE TITLE
link in "location" wont get <a> tag

### ISSUE THREAD

**Issue by abuhurayra** [pderksen/WP-Google-Calendar-Events#44]
Hello, 
First : thanks for your useful plugin
Second : I usually put link to google map in the location field of the calendar. And your plugin won't display it as a link, it display it as a normal text.
You can see an example of this problem on the site : http://ahlsunnah.com (The plugin is on the down right). The first link is in event/description, it displays correctly, the second line is in event/location.
I want to quick fix this, have you some indications ?
thanks

**Comment by nekojira** [comment]
if you are using Google's own location field you won't need to put a link to a map in your description

then you can use `[maps-link]` in the feed builder to return a map link pointing to Google Maps

alternatively instead of using html maybe you can write a link url (without `<a href='http://maps.google.com...'>my map</a>` but rather just `http://maps.google.com...` )

**Comment by abuhurayra** [comment]
Thanks for quick reply :+1: .
Maybe I wasn't clear : I don't use link to location in description field but I write the link in location field (without <a> tag).
[And I don't use google search engine for my places because google don't have these places referenced correctly.][And yes a work around is to put my location in description field]
If I write links in the description, it works very well as you pointed.
Example of event I use : 
Event name field : naveofevent
event description field : some description ...
event location field : mylocation http://google.maps/sOmEuRl

Can you tell me where I can insert a function (to add <a> tags to location field) in your plugin ?

**Comment by nekojira** [comment]
I see,

I think at the moment the plugin structure is a bit rigid and there's no hook to easily change the behaviour - I have plans to refactor the plugin for address these cases but it'll take some time

this is a list of the 'shortcode' entities that are parsed by the feed builder

https://github.com/pderksen/WP-Google-Calendar-Events/blob/d1bec7278d869b3bcf5a66cc8b8ec75ad60daacf/google-calendar-events/includes/class-gce-event.php#L232

as you can see one of them is the description

you could create a new one for your case

and later below tap into the switch
https://github.com/pderksen/WP-Google-Calendar-Events/blob/d1bec7278d869b3bcf5a66cc8b8ec75ad60daacf/google-calendar-events/includes/class-gce-event.php#L303

to add your shortcode case 

sorry if this is not enough for you, hope to improve the plugin in the future - we are collecting users feedback also for this purpose

cheers

**Comment by abuhurayra** [comment]
Thank you very much, I found out with your indication :+1: 
I modified your class-gce-event.php at line 339 and made it work like `case 'description'`
it was missing the fonction `make_clickable()`.
```
     case 'location':
				$location = esc_html( trim( $this->location ) );

				if ( $markdown || $html ) {
					if ( $markdown && function_exists( 'Markdown' ) )
						$location = Markdown( $location );

					if ( $html )
						$location = wp_kses_post( html_entity_decode( $location ) );
				} else {
					//Otherwise, preserve line breaks
					$location = nl2br( $location );

					//Make URLs clickable if required
					if ( $autolink )
							$location = make_clickable( $location );

				}
				return $m[1] . $location . $m[6];

```
Thanks you very much
